alter table WORKS_CONTAINER add constraint FK_WORKS_CONTAINER_ON_PACKING foreign key (PACKING_ID) references WORKS_PACKING(STOCK_ITEM_ID);
create index IDX_WORKS_CONTAINER_ON_PACKING on WORKS_CONTAINER (PACKING_ID);
