alter table WORKS_RAW_MATERIAL add constraint FK_WORKS_RAW_MATERIAL_SPEC_FILE foreign key (SPEC_FILE_ID) references SYS_FILE(ID);
alter table WORKS_RAW_MATERIAL add constraint FK_WORKS_RAW_MATERIAL_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID);
create index IDX_WORKS_RAW_MATERIAL_SPEC_FILE on WORKS_RAW_MATERIAL (SPEC_FILE_ID);
