alter table WORKS_WORKS_ORDER_LABLE add constraint FK_WORKS_ORDER_LABLE_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID);
alter table WORKS_WORKS_ORDER_LABLE add constraint FK_WORKS_ORDER_LABLE_LABLE foreign key (LABLE_ID) references WORKS_LABLE(STOCK_ITEM_ID);
create index IDX_WORKS_ORDER_LABLE_WORKS_ORDER on WORKS_WORKS_ORDER_LABLE (WORKS_ORDER_ID);
create index IDX_WORKS_ORDER_LABLE_LABLE on WORKS_WORKS_ORDER_LABLE (LABLE_ID);
