alter table WORKS_STOCK_COUNT_ITEM add constraint FK_WORKS_STOCK_COUNT_ITEM_STOCK_COUNT foreign key (STOCK_COUNT_ID) references WORKS_STOCK_COUNT(ID);
alter table WORKS_STOCK_COUNT_ITEM add constraint FK_WORKS_STOCK_COUNT_ITEM_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID);
create index IDX_WORKS_STOCK_COUNT_ITEM_STOCK_COUNT on WORKS_STOCK_COUNT_ITEM (STOCK_COUNT_ID);
create index IDX_WORKS_STOCK_COUNT_ITEM_STOCK_ITEM on WORKS_STOCK_COUNT_ITEM (STOCK_ITEM_ID);
