alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_PRODUCT foreign key (PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID);
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID);
create index IDX_WORKS_PRODUCT_CONTAINER_PRODUCT on WORKS_PRODUCT_CONTAINER (PRODUCT_ID);
create index IDX_WORKS_PRODUCT_CONTAINER_CONTAINER on WORKS_PRODUCT_CONTAINER (CONTAINER_ID);
