alter table WORKS_WORKS_ORDER_PACKING add constraint FK_WORKS_ORDER_PACKING_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID);
alter table WORKS_WORKS_ORDER_PACKING add constraint FK_WORKS_ORDER_PACKING_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID);
create index IDX_WORKS_ORDER_PACKING_WORKS_ORDER on WORKS_WORKS_ORDER_PACKING (WORKS_ORDER_ID);
create index IDX_WORKS_ORDER_PACKING_CONTAINER on WORKS_WORKS_ORDER_PACKING (CONTAINER_ID);
