alter table WORKS_STOCK_USAGE add constraint FK_WORKS_STOCK_USAGE_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID);
create index IDX_WORKS_STOCK_USAGE_STOCK_ITEM on WORKS_STOCK_USAGE (STOCK_ITEM_ID);
