alter table WORKS_PRICE_LIST add constraint FK_WORKS_PRICE_LIST_PRODUCT foreign key (PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID);
alter table WORKS_PRICE_LIST add constraint FK_WORKS_PRICE_LIST_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID);
create index IDX_WORKS_PRICE_LIST_PRODUCT on WORKS_PRICE_LIST (PRODUCT_ID);
create index IDX_WORKS_PRICE_LIST_CONTAINER on WORKS_PRICE_LIST (CONTAINER_ID);
