alter table WORKS_PRODUCT_CONTAINER add column CORROSIVE_LABEL_ID uuid ;
alter table WORKS_PRODUCT_CONTAINER add column FLAMMABLE_LABEL_ID uuid ;
alter table WORKS_PRODUCT_CONTAINER add column POISONOUS_LABEL_ID uuid ;
alter table WORKS_PRODUCT_CONTAINER add column KEEP_AWAY_LABEL_ID uuid ;
alter table WORKS_PRODUCT_CONTAINER add column PRODUCT_LABEL_ID uuid ;
