alter table WORKS_WORKS_ORDER_KEY add constraint FK_WORKS_ORDER_KEY_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID);
create index IDX_WORKS_ORDER_KEY_WORKS_ORDER on WORKS_WORKS_ORDER_KEY (WORKS_ORDER_ID);
