-- begin WORKS_CATEGORY
create unique index IDX_WORKS_CATEGORY_UK_CODE on WORKS_CATEGORY (CODE) where DELETE_TS is null ^
create unique index IDX_WORKS_CATEGORY_UK_DESCRIPTION on WORKS_CATEGORY (DESCRIPTION) where DELETE_TS is null ^
-- end WORKS_CATEGORY
-- begin WORKS_ORDER
alter table WORKS_ORDER add constraint FK_WORKS_ORDER_ON_PRODUCT foreign key (PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID)^
alter table WORKS_ORDER add constraint FK_WORKS_ORDER_ON_MIXER foreign key (MIXER_ID) references WORKS_MIXER(ID)^
alter table WORKS_ORDER add constraint FK_WORKS_ORDER_ON_DECANTED_PRODUCT foreign key (DECANTED_PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID)^
alter table WORKS_ORDER add constraint FK_WORKS_ORDER_ON_PRODUCT foreign key (PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID)^
alter table WORKS_ORDER add constraint FK_WORKS_ORDER_ON_MIXER foreign key (MIXER_ID) references WORKS_MIXER(ID)^
create unique index IDX_WORKS_ORDER_UK_DOCUMENT_NO on WORKS_ORDER (DOCUMENT_NO) where DELETE_TS is null ^
create index IDX_WORKS_ORDER_ON_PRODUCT on WORKS_ORDER (PRODUCT_ID)^
create index IDX_WORKS_ORDER_ON_MIXER on WORKS_ORDER (MIXER_ID)^
create index IDX_WORKS_ORDER_ON_DECANTED_PRODUCT on WORKS_ORDER (DECANTED_PRODUCT_ID)^
-- end WORKS_ORDER
-- begin WORKS_STOCK_ITEM
create unique index IDX_WORKS_STOCK_ITEM_UK_CODE on WORKS_STOCK_ITEM (CODE) where DELETE_TS is null ^
-- end WORKS_STOCK_ITEM
-- begin WORKS_MIXER
create unique index IDX_WORKS_MIXER_UK_NAME on WORKS_MIXER (NAME) where DELETE_TS is null ^
-- end WORKS_MIXER
-- begin WORKS_CONTAINER
alter table WORKS_CONTAINER add constraint FK_WORKS_CONTAINER_ON_PACKING foreign key (PACKING_ID) references WORKS_PACKING(STOCK_ITEM_ID)^
alter table WORKS_CONTAINER add constraint FK_WORKS_CONTAINER_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID) on delete CASCADE^
create index IDX_WORKS_CONTAINER_ON_PACKING on WORKS_CONTAINER (PACKING_ID)^
-- end WORKS_CONTAINER
-- begin WORKS_RAW_MATERIAL
alter table WORKS_RAW_MATERIAL add constraint FK_WORKS_RAW_MATERIAL_ON_SPEC_FILE foreign key (SPEC_FILE_ID) references SYS_FILE(ID)^
alter table WORKS_RAW_MATERIAL add constraint FK_WORKS_RAW_MATERIAL_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID) on delete CASCADE^
create index IDX_WORKS_RAW_MATERIAL_ON_SPEC_FILE on WORKS_RAW_MATERIAL (SPEC_FILE_ID)^
-- end WORKS_RAW_MATERIAL
-- begin WORKS_PRODUCT
alter table WORKS_PRODUCT add constraint FK_WORKS_PRODUCT_ON_CATEGORY foreign key (CATEGORY_ID) references WORKS_CATEGORY(ID)^
alter table WORKS_PRODUCT add constraint FK_WORKS_PRODUCT_ON_SPEC_FILE foreign key (SPEC_FILE_ID) references SYS_FILE(ID)^
alter table WORKS_PRODUCT add constraint FK_WORKS_PRODUCT_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID) on delete CASCADE^
create index IDX_WORKS_PRODUCT_ON_CATEGORY on WORKS_PRODUCT (CATEGORY_ID)^
create index IDX_WORKS_PRODUCT_ON_SPEC_FILE on WORKS_PRODUCT (SPEC_FILE_ID)^
-- end WORKS_PRODUCT
-- begin WORKS_LABLE
alter table WORKS_LABLE add constraint FK_WORKS_LABLE_ON_IMAGE_FILE foreign key (IMAGE_FILE_ID) references SYS_FILE(ID)^
alter table WORKS_LABLE add constraint FK_WORKS_LABLE_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID) on delete CASCADE^
create index IDX_WORKS_LABLE_ON_IMAGE_FILE on WORKS_LABLE (IMAGE_FILE_ID)^
-- end WORKS_LABLE
-- begin WORKS_WORKS_ORDER_PACKING
alter table WORKS_WORKS_ORDER_PACKING add constraint FK_WORKS_ORDER_PACKING_ON_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_WORKS_ORDER_PACKING add constraint FK_WORKS_ORDER_PACKING_ON_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID)^
create index IDX_WORKS_ORDER_PACKING_ON_WORKS_ORDER on WORKS_WORKS_ORDER_PACKING (WORKS_ORDER_ID)^
create index IDX_WORKS_ORDER_PACKING_ON_CONTAINER on WORKS_WORKS_ORDER_PACKING (CONTAINER_ID)^
-- end WORKS_WORKS_ORDER_PACKING
-- begin WORKS_WORKS_ORDER_INGREDIENT
alter table WORKS_WORKS_ORDER_INGREDIENT add constraint FK_WORKS_ORDER_INGREDIENT_ON_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_WORKS_ORDER_INGREDIENT add constraint FK_WORKS_ORDER_INGREDIENT_ON_RAW_MATERIAL foreign key (RAW_MATERIAL_ID) references WORKS_RAW_MATERIAL(STOCK_ITEM_ID)^
create unique index IDX_WORKS_WORKS_ORDER_INGREDIENT_UNQ on WORKS_WORKS_ORDER_INGREDIENT (WORKS_ORDER_ID, SEQUENCE_NO) where DELETE_TS is null ^
create index IDX_WORKS_ORDER_INGREDIENT_ON_WORKS_ORDER on WORKS_WORKS_ORDER_INGREDIENT (WORKS_ORDER_ID)^
create index IDX_WORKS_ORDER_INGREDIENT_ON_RAW_MATERIAL on WORKS_WORKS_ORDER_INGREDIENT (RAW_MATERIAL_ID)^
-- end WORKS_WORKS_ORDER_INGREDIENT
-- begin WORKS_WORKS_ORDER_LABLE
alter table WORKS_WORKS_ORDER_LABLE add constraint FK_WORKS_ORDER_LABLE_ON_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_WORKS_ORDER_LABLE add constraint FK_WORKS_ORDER_LABLE_ON_LABLE foreign key (LABLE_ID) references WORKS_LABLE(STOCK_ITEM_ID)^
create index IDX_WORKS_ORDER_LABLE_ON_WORKS_ORDER on WORKS_WORKS_ORDER_LABLE (WORKS_ORDER_ID)^
create index IDX_WORKS_ORDER_LABLE_ON_LABLE on WORKS_WORKS_ORDER_LABLE (LABLE_ID)^
-- end WORKS_WORKS_ORDER_LABLE
-- begin WORKS_FORMULA
alter table WORKS_FORMULA add constraint FK_WORKS_FORMULA_ON_PRODUCT foreign key (PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID)^
alter table WORKS_FORMULA add constraint FK_WORKS_FORMULA_ON_RAW_MATERIAL foreign key (RAW_MATERIAL_ID) references WORKS_RAW_MATERIAL(STOCK_ITEM_ID)^
create unique index IDX_WORKS_FORMULA_UNQ on WORKS_FORMULA (PRODUCT_ID, SEQUENCE_NO) where DELETE_TS is null ^
create index IDX_WORKS_FORMULA_ON_PRODUCT on WORKS_FORMULA (PRODUCT_ID)^
create index IDX_WORKS_FORMULA_ON_RAW_MATERIAL on WORKS_FORMULA (RAW_MATERIAL_ID)^
-- end WORKS_FORMULA

-- begin WORKS_DECANTING_ORDER_TARGET
alter table WORKS_DECANTING_ORDER_TARGET add constraint FK_WORKS_DECANTING_ORDER_TARGET_ON_DECANTING_ORDER foreign key (DECANTING_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_DECANTING_ORDER_TARGET add constraint FK_WORKS_DECANTING_ORDER_TARGET_ON_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID)^
create index IDX_WORKS_DECANTING_ORDER_TARGET_ON_DECANTING_ORDER on WORKS_DECANTING_ORDER_TARGET (DECANTING_ORDER_ID)^
create index IDX_WORKS_DECANTING_ORDER_TARGET_ON_CONTAINER on WORKS_DECANTING_ORDER_TARGET (CONTAINER_ID)^
-- end WORKS_DECANTING_ORDER_TARGET
-- begin WORKS_SALES_ORDER_CONTAINER
alter table WORKS_SALES_ORDER_CONTAINER add constraint FK_WORKS_SALES_ORDER_CONTAINER_ON_SALES_ORDER foreign key (SALES_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_SALES_ORDER_CONTAINER add constraint FK_WORKS_SALES_ORDER_CONTAINER_ON_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID)^
create index IDX_WORKS_SALES_ORDER_CONTAINER_ON_SALES_ORDER on WORKS_SALES_ORDER_CONTAINER (SALES_ORDER_ID)^
create index IDX_WORKS_SALES_ORDER_CONTAINER_ON_CONTAINER on WORKS_SALES_ORDER_CONTAINER (CONTAINER_ID)^
-- end WORKS_SALES_ORDER_CONTAINER
-- begin WORKS_SALES_ORDER_RAW_MATERIAL
alter table WORKS_SALES_ORDER_RAW_MATERIAL add constraint FK_WORKS_SALES_ORDER_RAW_MATERIAL_ON_SALES_ORDER foreign key (SALES_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_SALES_ORDER_RAW_MATERIAL add constraint FK_WORKS_SALES_ORDER_RAW_MATERIAL_ON_RAW_MATERIAL foreign key (RAW_MATERIAL_ID) references WORKS_RAW_MATERIAL(STOCK_ITEM_ID)^
create index IDX_WORKS_SALES_ORDER_RAW_MATERIAL_ON_SALES_ORDER on WORKS_SALES_ORDER_RAW_MATERIAL (SALES_ORDER_ID)^
create index IDX_WORKS_SALES_ORDER_RAW_MATERIAL_ON_RAW_MATERIAL on WORKS_SALES_ORDER_RAW_MATERIAL (RAW_MATERIAL_ID)^
-- end WORKS_SALES_ORDER_RAW_MATERIAL
-- begin WORKS_STOCK_COUNT
create unique index IDX_WORKS_STOCK_COUNT_UK_DOCUMENT_NO on WORKS_STOCK_COUNT (DOCUMENT_NO) where DELETE_TS is null ^
-- end WORKS_STOCK_COUNT
-- begin WORKS_STOCK_COUNT_ITEM
alter table WORKS_STOCK_COUNT_ITEM add constraint FK_WORKS_STOCK_COUNT_ITEM_ON_STOCK_COUNT foreign key (STOCK_COUNT_ID) references WORKS_STOCK_COUNT(ID)^
alter table WORKS_STOCK_COUNT_ITEM add constraint FK_WORKS_STOCK_COUNT_ITEM_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID)^
create index IDX_WORKS_STOCK_COUNT_ITEM_ON_STOCK_COUNT on WORKS_STOCK_COUNT_ITEM (STOCK_COUNT_ID)^
create index IDX_WORKS_STOCK_COUNT_ITEM_ON_STOCK_ITEM on WORKS_STOCK_COUNT_ITEM (STOCK_ITEM_ID)^
-- end WORKS_STOCK_COUNT_ITEM
-- begin WORKS_STOCK_INTAKE_ITEM
alter table WORKS_STOCK_INTAKE_ITEM add constraint FK_WORKS_STOCK_INTAKE_ITEM_ON_STOCK_INTAKE foreign key (STOCK_INTAKE_ID) references WORKS_STOCK_INTAKE(ID)^
alter table WORKS_STOCK_INTAKE_ITEM add constraint FK_WORKS_STOCK_INTAKE_ITEM_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID)^
create index IDX_WORKS_STOCK_INTAKE_ITEM_ON_STOCK_INTAKE on WORKS_STOCK_INTAKE_ITEM (STOCK_INTAKE_ID)^
create index IDX_WORKS_STOCK_INTAKE_ITEM_ON_STOCK_ITEM on WORKS_STOCK_INTAKE_ITEM (STOCK_ITEM_ID)^
-- end WORKS_STOCK_INTAKE_ITEM
-- begin WORKS_SYSTEM_KEY
create unique index IDX_WORKS_SYSTEM_KEY_UNQ on WORKS_SYSTEM_KEY (CONTEXT) where DELETE_TS is null ^
-- end WORKS_SYSTEM_KEY
-- begin WORKS_PRODUCT_CONTAINER
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_ON_PRODUCT foreign key (PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID)^
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_ON_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID)^
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_ON_CORROSIVE_LABEL foreign key (CORROSIVE_LABEL_ID) references WORKS_LABLE(STOCK_ITEM_ID)^
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_ON_FLAMMABLE_LABEL foreign key (FLAMMABLE_LABEL_ID) references WORKS_LABLE(STOCK_ITEM_ID)^
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_ON_POISONOUS_LABEL foreign key (POISONOUS_LABEL_ID) references WORKS_LABLE(STOCK_ITEM_ID)^
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_ON_KEEP_AWAY_LABEL foreign key (KEEP_AWAY_LABEL_ID) references WORKS_LABLE(STOCK_ITEM_ID)^
alter table WORKS_PRODUCT_CONTAINER add constraint FK_WORKS_PRODUCT_CONTAINER_ON_PRODUCT_LABEL foreign key (PRODUCT_LABEL_ID) references WORKS_LABLE(STOCK_ITEM_ID)^
create index IDX_WORKS_PRODUCT_CONTAINER_ON_PRODUCT on WORKS_PRODUCT_CONTAINER (PRODUCT_ID)^
create index IDX_WORKS_PRODUCT_CONTAINER_ON_CONTAINER on WORKS_PRODUCT_CONTAINER (CONTAINER_ID)^
create index IDX_WORKS_PRODUCT_CONTAINER_ON_CORROSIVE_LABEL on WORKS_PRODUCT_CONTAINER (CORROSIVE_LABEL_ID)^
create index IDX_WORKS_PRODUCT_CONTAINER_ON_FLAMMABLE_LABEL on WORKS_PRODUCT_CONTAINER (FLAMMABLE_LABEL_ID)^
create index IDX_WORKS_PRODUCT_CONTAINER_ON_POISONOUS_LABEL on WORKS_PRODUCT_CONTAINER (POISONOUS_LABEL_ID)^
create index IDX_WORKS_PRODUCT_CONTAINER_ON_KEEP_AWAY_LABEL on WORKS_PRODUCT_CONTAINER (KEEP_AWAY_LABEL_ID)^
create index IDX_WORKS_PRODUCT_CONTAINER_ON_PRODUCT_LABEL on WORKS_PRODUCT_CONTAINER (PRODUCT_LABEL_ID)^
-- end WORKS_PRODUCT_CONTAINER
-- begin WORKS_PRICE_UPDATE
create unique index IDX_WORKS_PRICE_UPDATE_UK_DOCUMENT_NO on WORKS_PRICE_UPDATE (DOCUMENT_NO) where DELETE_TS is null ^
-- end WORKS_PRICE_UPDATE
-- begin WORKS_PRICE_UPDATE_ITEM
alter table WORKS_PRICE_UPDATE_ITEM add constraint FK_WORKS_PRICE_UPDATE_ITEM_ON_PRICE_UPDATE foreign key (PRICE_UPDATE_ID) references WORKS_PRICE_UPDATE(ID)^
alter table WORKS_PRICE_UPDATE_ITEM add constraint FK_WORKS_PRICE_UPDATE_ITEM_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID)^
create index IDX_WORKS_PRICE_UPDATE_ITEM_ON_PRICE_UPDATE on WORKS_PRICE_UPDATE_ITEM (PRICE_UPDATE_ID)^
create index IDX_WORKS_PRICE_UPDATE_ITEM_ON_STOCK_ITEM on WORKS_PRICE_UPDATE_ITEM (STOCK_ITEM_ID)^
-- end WORKS_PRICE_UPDATE_ITEM
-- begin WORKS_STOCK_USAGE
alter table WORKS_STOCK_USAGE add constraint FK_WORKS_STOCK_USAGE_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID)^
create index IDX_WORKS_STOCK_USAGE_ON_STOCK_ITEM on WORKS_STOCK_USAGE (STOCK_ITEM_ID)^
-- end WORKS_STOCK_USAGE
-- begin WORKS_PRICE_LIST
alter table WORKS_PRICE_LIST add constraint FK_WORKS_PRICE_LIST_ON_PRODUCT foreign key (PRODUCT_ID) references WORKS_PRODUCT(STOCK_ITEM_ID)^
alter table WORKS_PRICE_LIST add constraint FK_WORKS_PRICE_LIST_ON_CONTAINER foreign key (CONTAINER_ID) references WORKS_CONTAINER(STOCK_ITEM_ID)^
create index IDX_WORKS_PRICE_LIST_ON_PRODUCT on WORKS_PRICE_LIST (PRODUCT_ID)^
create index IDX_WORKS_PRICE_LIST_ON_CONTAINER on WORKS_PRICE_LIST (CONTAINER_ID)^
-- end WORKS_PRICE_LIST
-- begin WORKS_CALENDAR
create unique index IDX_WORKS_CALENDAR_UK_THE_DATE on WORKS_CALENDAR (THE_DATE) where DELETE_TS is null ^
-- end WORKS_CALENDAR
-- begin WORKS_WORKS_ORDER_KEY
alter table WORKS_WORKS_ORDER_KEY add constraint FK_WORKS_ORDER_KEY_ON_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_WORKS_ORDER_KEY add constraint FK_WORKS_ORDER_KEY_ON_MANUFACTURING_KEY foreign key (MANUFACTURING_KEY_ID) references WORKS_INSTRUCTION(ID)^
create index IDX_WORKS_ORDER_KEY_ON_WORKS_ORDER on WORKS_WORKS_ORDER_KEY (WORKS_ORDER_ID)^
create index IDX_WORKS_ORDER_KEY_ON_MANUFACTURING_KEY on WORKS_WORKS_ORDER_KEY (MANUFACTURING_KEY_ID)^
-- end WORKS_WORKS_ORDER_KEY
-- begin WORKS_INTERMEDIATE_ORDER_INGREDIENT
alter table WORKS_INTERMEDIATE_ORDER_INGREDIENT add constraint FK_WORKS_INTERMEDIATE_ORDER_INGREDIENT_ON_INTERMEDIATE_ORDER foreign key (INTERMEDIATE_ORDER_ID) references WORKS_ORDER(ID)^
alter table WORKS_INTERMEDIATE_ORDER_INGREDIENT add constraint FK_WORKS_INTERMEDIATE_ORDER_INGREDIENT_ON_RAW_MATERIAL foreign key (RAW_MATERIAL_ID) references WORKS_RAW_MATERIAL(STOCK_ITEM_ID)^
create index IDX_WORKS_INTERMEDIATE_ORDER_INGREDIENT_ON_INTERMEDIATE_ORDER on WORKS_INTERMEDIATE_ORDER_INGREDIENT (INTERMEDIATE_ORDER_ID)^
create index IDX_WORKS_INTERMEDIATE_ORDER_INGREDIENT_ON_RAW_MATERIAL on WORKS_INTERMEDIATE_ORDER_INGREDIENT (RAW_MATERIAL_ID)^
-- end WORKS_INTERMEDIATE_ORDER_INGREDIENT

-- begin WORKS_INSTRUCTION
create unique index IDX_WORKS_INSTRUCTION_UK_NAME on WORKS_INSTRUCTION (NAME) where DELETE_TS is null ^
-- end WORKS_INSTRUCTION
-- begin WORKS_PACKING
alter table WORKS_PACKING add constraint FK_WORKS_PACKING_ON_STOCK_ITEM foreign key (STOCK_ITEM_ID) references WORKS_STOCK_ITEM(ID) on delete CASCADE^
-- end WORKS_PACKING
