alter table WORKS_WORKS_ORDER_SHIPPER add constraint FK_WORKS_ORDER_SHIPPER_ON_WORKS_ORDER foreign key (WORKS_ORDER_ID) references WORKS_ORDER(ID);
alter table WORKS_WORKS_ORDER_SHIPPER add constraint FK_WORKS_ORDER_SHIPPER_ON_PACKING foreign key (PACKING_ID) references WORKS_PACKING(STOCK_ITEM_ID);
create index IDX_WORKS_ORDER_SHIPPER_ON_WORKS_ORDER on WORKS_WORKS_ORDER_SHIPPER (WORKS_ORDER_ID);
create index IDX_WORKS_ORDER_SHIPPER_ON_PACKING on WORKS_WORKS_ORDER_SHIPPER (PACKING_ID);
